name: chessml
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.9.9
  - expat=2.7.1
  - imbalanced-learn=0.12.4
  - joblib=1.5.2
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.4.4
  - libhwloc=2.12.1
  - libiconv=1.18
  - liblapack=3.9.0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxml2=2.13.8
  - libzlib=1.3.1
  - llvm-openmp=21.1.2
  - mkl=2024.2.2
  - openssl=3.5.4
  - pandas=2.2.3
  - pip=25.2
  - python=3.10.18
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.10
  - pytz=2025.2
  - scikit-learn=1.5.2
  - setuptools=78.1.1
  - six=1.17.0
  - sqlite=3.50.2
  - tbb=2021.13.0
  - threadpoolctl=3.6.0
  - tk=8.6.15
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - absl-py==2.3.1
      - asttokens==3.0.0
      - astunparse==1.6.3
      - cachetools==6.2.0
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - chess==1.11.2
      - colorama==0.4.6
      - comm==0.2.3
      - contourpy==1.3.2
      - cycler==0.12.1
      - debugpy==1.8.17
      - decorator==5.2.1
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - flatbuffers==25.9.23
      - fonttools==4.60.1
      - gast==0.4.0
      - google-auth==2.41.1
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - grpcio==1.74.0
      - h5py==3.14.0
      - idna==3.10
      - ipykernel==6.30.1
      - ipython==8.37.0
      - jedi==0.19.2
      - jupyter-client==8.6.3
      - jupyter-core==5.8.1
      - keras==3.4.1
      - kiwisolver==1.4.9
      - libclang==18.1.1
      - markdown==3.9
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.6
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - ml-dtypes==0.3.2
      - namex==0.1.0
      - nest-asyncio==1.6.0
      - numpy==1.26.4
      - oauthlib==3.3.1
      - opt-einsum==3.4.0
      - optree==0.17.0
      - packaging==25.0
      - parso==0.8.5
      - pillow==11.3.0
      - platformdirs==4.4.0
      - prompt-toolkit==3.0.52
      - protobuf==4.25.3
      - psutil==7.1.0
      - pure-eval==0.2.3
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pygments==2.19.2
      - pyparsing==3.2.5
      - python-chess==1.999
      - pywin32==311
      - pyzmq==27.1.0
      - requests==2.32.5
      - requests-oauthlib==2.0.0
      - rich==14.1.0
      - rsa==4.9.1
      - scipy==1.15.3
      - seaborn==0.13.2
      - stack-data==0.6.3
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - tensorflow==2.16.1
      - tensorflow-estimator==2.13.0
      - tensorflow-intel==2.16.1
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==3.1.0
      - tornado==6.5.2
      - traitlets==5.14.3
      - typing-extensions==4.15.0
      - urllib3==2.5.0
      - wcwidth==0.2.14
      - werkzeug==3.1.3
      - wrapt==1.17.3
